[settings]
server = "http://injector:5050/api/v1/push"
log_level = "trace"
scan_existing = false

[[files]]
path = "logs/"
positions_file = "./scratch/logs_positions.toml"
file_regex = "InterfaceAdapter*.log"
labels.app_name = "Interface Adapter"
labels.component = "Nils"
forward_frequency_ms= 2000
